apiVersion: v1
kind: Service
metadata:
  name: consulta-cep-service
  labels:
    app: consulta-cep-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: consulta-cep-service
  type: LoadBalancer
