name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests
      run: cd cep-service && mvn test

  build_docker_image:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}  

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./cep-service
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/via-cep-service:${{ github.sha }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/via-cep-service:latest
    
    - name: Deploy to Render
      run: |
        RENDER_URL=$(curl -s https://api.render.com/v1/projects/${{ secrets.RENDER_PROJECT_ID }}/services/${{ secrets.RENDER_SERVICE_ID }} | jq -r '.url')
        RENDER_ACCESS_TOKEN=$(echo "${{ secrets.RENDER_API_KEY }}" | base64 -d)
        curl -X POST -H "Authorization: Bearer ${RENDER_ACCESS_TOKEN}" -H "Content-Type: application/json" -d '{ "image": "${{ secrets.DOCKER_HUB_USERNAME }}/via-cep-service:${{ github.sha }}" }' "${RENDER_URL}/deploy"               